### PR TITLE
fixed the crashing 

### PR DESCRIPTION
**Pull request by TheDisabledKid**
i fixed the problem that you have

### CODE REVIEW

**Comment by Tr1NgleDev** [comment]
what was the problem 💀 . everything was ok lol

**Comment by Tr1NgleDev** [comment]
and i actually cant add these "fixes" in TE because im making big update rn lol.

**Comment by Tr1NgleDev** [comment]
and i dont have any problems

**Comment by TheDisabledKid** [comment]
oh lol

**Pull request closed without merging**
