### PR TITLE
No deprecation warnings

### PR DESCRIPTION
**Pull request by MemeHoovy**

### CODE REVIEW

**Comment by Tr1NgleDev** [comment]
hmm?
i dont think that its that big thing to add. i dont even think if it will change something much

**Comment by MemeHoovy** [comment]
it just removes deprecation warnings whenever you compile the game

**Comment by Tr1NgleDev** [comment]
Ok i can add it to 1.7.5 but not sure if i can merge it because i already did some changes to my local repo

**Comment by Stilic** [comment]
don't merge that
warnings are userful when you want your code to work with the latest versions of the librairies

**Comment by Stilic** [comment]
+ they can be easily fixed without hiding them

**Comment by MemeHoovy** [comment]
> don't merge that
> warnings are userful when you want your code to work with the latest versions of the librairies

yeah but I just use this instead of fixing them (I’m too lazy)

**Comment by Stilic** [comment]
> 

so you prefer the code to be incompatible in the future instead?
see this: https://medium.com/it-dead-inside/why-i-always-treat-warnings-as-errors-5895fb7f8600

**Comment by MemeHoovy** [comment]
> > 
> 
> so you prefer the code to be incompatible in the future instead? see this: https://medium.com/it-dead-inside/why-i-always-treat-warnings-as-errors-5895fb7f8600

I know I should treat those deprecation warnings as a problem, but I don't fix them and just use that to remove them (too lazy)

**Comment by MemeHoovy** [comment]
196077253-e3b7bd23-cae4-4419-9a7f-c156e67c3dbc (2)

**Comment by Stilic** [comment]
> > > 
> > 
> > 
> > so you prefer the code to be incompatible in the future instead? see this: https://medium.com/it-dead-inside/why-i-always-treat-warnings-as-errors-5895fb7f8600
> 
> I know I should treat those deprecation warnings as a problem, but I don't fix them and just use that to remove them (I'mtoo lazy :p)

Please close this then.
This is totally useless.

**Pull request closed without merging**
